"""
orchestrator.py — AI Employee Brain (Bronze Tier)
Reads tasks from Needs_Action/, processes with Claude API, 
writes drafts to Pending_Approval/ for human review.

Run: python orchestrator.py --vault .
"""

import os
import time
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime

import anthropic

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(), logging.FileHandler("orchestrator.log")],
)
logger = logging.getLogger("Orchestrator")


def read_handbook(vault: Path) -> str:
    """Load Company_Handbook.md for AI rules"""
    handbook = vault / "Company_Handbook.md"
    if handbook.exists():
        return handbook.read_text(encoding="utf-8")
    return "Be professional. Flag sensitive actions. Always require human approval."


def read_task(task_file: Path) -> str:
    """Read a task .md file"""
    return task_file.read_text(encoding="utf-8")


def process_task_with_claude(task_content: str, handbook: str, client: anthropic.Anthropic) -> str:
    """Send task to Claude API and get a response plan"""
    system_prompt = f"""You are a professional AI Employee assistant. 
You follow these company rules strictly:

{handbook}

When given a task, you must:
1. Analyze what needs to be done
2. Draft a professional response or action plan
3. NEVER take sensitive actions directly — always create an approval request
4. Be concise and professional

Format your response as:
## Analysis
[brief analysis of the task]

## Proposed Action
[what you plan to do]

## Draft Response (if applicable)
[draft email/message/document]

## Approval Required
[what the human needs to approve before proceeding]
"""
    message = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=1000,
        system=system_prompt,
        messages=[{"role": "user", "content": f"Process this task:\n\n{task_content}"}],
    )
    return message.content[0].text


def create_approval_file(vault: Path, task_file: Path, ai_response: str) -> Path:
    """Write AI plan to Pending_Approval/ for human review"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    approval_name = f"APPROVAL_{timestamp}_{task_file.stem}.md"
    approval_path = vault / "Pending_Approval" / approval_name

    content = f"""---
type: approval_request
original_task: {task_file.name}
created: {datetime.now().isoformat()}
status: pending_human_approval
---

# ⏳ Awaiting Your Approval

Review the AI's plan below. To approve, move this file to `Done/`. 
To reject, delete this file.

---

## Original Task
From: `{task_file.name}`

---

## AI Employee Plan

{ai_response}

---

*Generated by AI Employee Orchestrator — {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
    approval_path.write_text(content, encoding="utf-8")
    logger.info(f"📋 Approval request created: {approval_name}")
    return approval_path


def archive_task(task_file: Path, done_folder: Path):
    """Move processed task to Done/"""
    dest = done_folder / task_file.name
    task_file.rename(dest)
    logger.info(f"✅ Task archived to Done/: {task_file.name}")


def update_dashboard(vault: Path, processed: int, pending: int):
    """Update Dashboard.md with current status"""
    dashboard = vault / "Dashboard.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pending_count = len(list((vault / "Pending_Approval").glob("APPROVAL_*.md")))
    needs_count = len(list((vault / "Needs_Action").glob("*.md")))

    content = f"""# 🤖 AI Employee Dashboard

## Status
- Last Updated: {now}
- Active Tasks: {needs_count}
- Pending Approvals: {pending_count}
- Total Processed This Session: {processed}

## Watcher Status
- Orchestrator: ✅ ACTIVE
- Last Run: {now}

## Today's Summary
Orchestrator is running. Tasks in Needs_Action/ are being processed automatically.
Check Pending_Approval/ for items requiring your review.
"""
    dashboard.write_text(content, encoding="utf-8")


def log_action(vault: Path, task_name: str, action: str, result: str):
    """Append to audit log"""
    log_dir = vault / "Logs"
    log_dir.mkdir(exist_ok=True)
    log_file = log_dir / f"{datetime.now().strftime('%Y-%m-%d')}.json"

    entry = {
        "timestamp": datetime.now().isoformat(),
        "task": task_name,
        "action": action,
        "result": result,
        "actor": "claude_orchestrator",
    }
    entries = []
    if log_file.exists():
        try:
            entries = json.loads(log_file.read_text())
        except Exception:
            entries = []
    entries.append(entry)
    log_file.write_text(json.dumps(entries, indent=2))


def run(vault_path: str, interval: int = 15):
    vault = Path(vault_path)
    needs_action = vault / "Needs_Action"
    pending = vault / "Pending_Approval"
    done = vault / "Done"

    for folder in [needs_action, pending, done, vault / "Logs"]:
        folder.mkdir(parents=True, exist_ok=True)

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        logger.error("❌ ANTHROPIC_API_KEY not set! Run: export ANTHROPIC_API_KEY=your-key")
        return

    client = anthropic.Anthropic(api_key=api_key)
    handbook = read_handbook(vault)
    processed_count = 0

    logger.info(f"🤖 Orchestrator started. Vault: {vault.resolve()}")
    logger.info(f"⏱️  Processing interval: {interval}s")
    logger.info("Waiting for tasks in Needs_Action/...")

    while True:
        try:
            tasks = [
                f for f in needs_action.glob("*.md")
                if f.name != ".gitkeep" and not f.name.startswith(".")
            ]

            for task_file in tasks:
                logger.info(f"🧠 Processing: {task_file.name}")
                task_content = read_task(task_file)
                
                try:
                    ai_response = process_task_with_claude(task_content, handbook, client)
                    create_approval_file(vault, task_file, ai_response)
                    archive_task(task_file, done)
                    processed_count += 1
                    log_action(vault, task_file.name, "processed", "approval_created")
                    logger.info(f"✅ Done. Approval file created for human review.")
                except Exception as e:
                    logger.error(f"Claude API error for {task_file.name}: {e}")
                    log_action(vault, task_file.name, "error", str(e))

            update_dashboard(vault, processed_count, len(list(pending.glob("APPROVAL_*.md"))))

        except Exception as e:
            logger.error(f"Orchestrator error: {e}")

        time.sleep(interval)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AI Employee — Orchestrator")
    parser.add_argument("--vault", default=".", help="Path to vault folder")
    parser.add_argument("--interval", type=int, default=15, help="Processing interval (seconds)")
    args = parser.parse_args()

    try:
        run(args.vault, args.interval)
    except KeyboardInterrupt:
        logger.info("👋 Orchestrator stopped by user.")
