"""
orchestrator.py — AI Employee Brain (Bronze Tier)
Uses Google Gemini API (FREE) instead of Anthropic
Run: python orchestrator.py --vault .
"""

import os
import time
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime

import google.generativeai as genai

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(), logging.FileHandler("orchestrator.log")],
    encoding="utf-8",
)
logger = logging.getLogger("Orchestrator")


def read_handbook(vault: Path) -> str:
    handbook = vault / "Company_Handbook.md"
    if handbook.exists():
        return handbook.read_text(encoding="utf-8")
    return "Be professional. Flag sensitive actions. Always require human approval."


def read_task(task_file: Path) -> str:
    return task_file.read_text(encoding="utf-8")


def process_task_with_gemini(task_content: str, handbook: str, model) -> str:
    prompt = f"""You are a professional AI Employee assistant.
You follow these company rules strictly:

{handbook}

When given a task, you must:
1. Analyze what needs to be done
2. Draft a professional response or action plan
3. NEVER take sensitive actions directly — always create an approval request
4. Be concise and professional

Format your response as:
## Analysis
[brief analysis of the task]

## Proposed Action
[what you plan to do]

## Draft Response (if applicable)
[draft email/message/document]

## Approval Required
[what the human needs to approve before proceeding]

Now process this task:

{task_content}"""

    response = model.generate_content(prompt)
    return response.text


def create_approval_file(vault: Path, task_file: Path, ai_response: str) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    approval_name = f"APPROVAL_{timestamp}_{task_file.stem}.md"
    approval_path = vault / "Pending_Approval" / approval_name

    content = f"""---
type: approval_request
original_task: {task_file.name}
created: {datetime.now().isoformat()}
status: pending_human_approval
---

# Awaiting Your Approval

Review the AI's plan below. Move this file to Done/ to approve.

---

## Original Task
From: `{task_file.name}`

---

## AI Employee Plan

{ai_response}

---

*Generated by AI Employee Orchestrator — {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
    approval_path.write_text(content, encoding="utf-8")
    logger.info(f"Approval request created: {approval_name}")
    return approval_path


def archive_task(task_file: Path, done_folder: Path):
    dest = done_folder / task_file.name
    task_file.rename(dest)
    logger.info(f"Task archived to Done/: {task_file.name}")


def update_dashboard(vault: Path, processed: int):
    dashboard = vault / "Dashboard.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pending_count = len(list((vault / "Pending_Approval").glob("APPROVAL_*.md")))
    needs_count = len(list((vault / "Needs_Action").glob("*.md")))

    content = f"""# AI Employee Dashboard

## Status
- Last Updated: {now}
- Active Tasks: {needs_count}
- Pending Approvals: {pending_count}
- Total Processed This Session: {processed}

## Watcher Status
- Orchestrator: ACTIVE
- Last Run: {now}

## Today's Summary
Orchestrator running. Check Pending_Approval/ for items requiring your review.
"""
    dashboard.write_text(content, encoding="utf-8")


def log_action(vault: Path, task_name: str, action: str, result: str):
    log_dir = vault / "Logs"
    log_dir.mkdir(exist_ok=True)
    log_file = log_dir / f"{datetime.now().strftime('%Y-%m-%d')}.json"
    entry = {
        "timestamp": datetime.now().isoformat(),
        "task": task_name,
        "action": action,
        "result": result,
        "actor": "gemini_orchestrator",
    }
    entries = []
    if log_file.exists():
        try:
            entries = json.loads(log_file.read_text())
        except Exception:
            entries = []
    entries.append(entry)
    log_file.write_text(json.dumps(entries, indent=2))


def run(vault_path: str, interval: int = 15):
    vault = Path(vault_path)
    needs_action = vault / "Needs_Action"
    pending = vault / "Pending_Approval"
    done = vault / "Done"

    for folder in [needs_action, pending, done, vault / "Logs"]:
        folder.mkdir(parents=True, exist_ok=True)

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        logger.error("GEMINI_API_KEY not set! Run: $env:GEMINI_API_KEY='your-key'")
        return

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-1.5-flash")
    handbook = read_handbook(vault)
    processed_count = 0

    logger.info(f"Orchestrator started. Vault: {vault.resolve()}")
    logger.info(f"Processing interval: {interval}s")
    logger.info("Waiting for tasks in Needs_Action/...")

    while True:
        try:
            tasks = [
                f for f in needs_action.glob("*.md")
                if f.name != ".gitkeep" and not f.name.startswith(".")
            ]
            for task_file in tasks:
                logger.info(f"Processing: {task_file.name}")
                task_content = read_task(task_file)
                try:
                    ai_response = process_task_with_gemini(task_content, handbook, model)
                    create_approval_file(vault, task_file, ai_response)
                    archive_task(task_file, done)
                    processed_count += 1
                    log_action(vault, task_file.name, "processed", "approval_created")
                    logger.info("Done. Approval file created for human review.")
                except Exception as e:
                    logger.error(f"Gemini API error for {task_file.name}: {e}")
                    log_action(vault, task_file.name, "error", str(e))

            update_dashboard(vault, processed_count)

        except Exception as e:
            logger.error(f"Orchestrator error: {e}")

        time.sleep(interval)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AI Employee Orchestrator (Gemini)")
    parser.add_argument("--vault", default=".", help="Path to vault folder")
    parser.add_argument("--interval", type=int, default=15, help="Processing interval (seconds)")
    args = parser.parse_args()
    try:
        run(args.vault, args.interval)
    except KeyboardInterrupt:
        logger.info("Orchestrator stopped.")
